define(['underscore',
  'jquery',
  'backbone',
  'marionette',
  'js/components/api_query',
'js/widgets/base/base_widget',
 'hbs!./templates/resources_template',
  'js/mixins/link_generator_mixin'
], function(_, $, Backbone, Marionette, ApiQuery, BaseWidget, ResourcesTemplate, LinkGenerator){


  var ResourcesModel = Backbone.Model.extend({

  })


  var ResourcesView = Marionette.ItemView.extend({

    template : ResourcesTemplate,

    modelEvents: {
      "change": "render"
    }

  })


  var ResourcesWidget = BaseWidget.extend({

    initialize : function(options){
      options = options || {};
      this.model = new ResourcesModel();
      this.view = new ResourcesView({model : this.model});

      this._bibcode = options.bibcode || undefined;

      _.bindAll(this, "processResponse");

      this.showLoad = true;
    },

    activate: function (beehive) {
      this.pubsub = beehive.Services.get('PubSub');

      this.pubsub.subscribe(this.pubsub.DELIVERING_RESPONSE, this.processResponse);
    },

    loadBibcodeData : function(bibcode){

      if (bibcode === this._bibcode){

        this.deferredObject =  $.Deferred();
        this.deferredObject.resolve(this.model);
        return this.deferredObject.promise();

      }
      else {
        this._bibcode = bibcode;

        var searchTerm = "bibcode:"+this._bibcode;

        this.deferredObject =  $.Deferred();
        //abstractPageFields comes from the LinkGenerator Mixin

        this.dispatchRequest(new ApiQuery({'q': searchTerm, fl : "links_data,ids_data,[citations],property,bibcode"}));
        return this.deferredObject.promise();
      }

    },

    processResponse : function(apiResponse){

      var data = apiResponse.get("response.docs[0]");

      //from link mixin
      data = this.parseResourcesData(data);

      this.model.set(data);

      //resolving the promises generated by "loadBibcodeData"
      if (this.deferredObject){
        this.deferredObject.resolve(this.model)
      }

    }

  })

  _.extend(ResourcesWidget.prototype, LinkGenerator);


 return ResourcesWidget

})