define([
  'js/widgets/network_vis/network_widget'
], function(
  NetworkWidget
  ) {

  var options = {};

  options.endpoint = "services/vis/author-network";

  options.helpText = "<p>If your result set is large enough, you will see a summary graph made up of author groups." +
    "These groups are generated by a community detection algorithm, and their sizes represent the cumulative " +
    "frequency of occurence in the result set of all their members. (In other words: people who " +
    "co-author papers together, appear in the same cluster. The bigger the cluster, the more " +
    "frequent is that name in the result set.) </p>";

  options.networkType = "author";

  return function(){

    return new NetworkWidget(options);

  };



});
