define([], function() {

  var tests  = [
      '/page_managers/all_tests.spec.js',
      '/page_managers/toc_controller.spec.js',
      '/page_managers/toc_manager_test.spec.js',
      '/widgets/authentication_widget.spec.js',
      '/widgets/abstract_widget.spec.js',
      '/widgets/alerts_widget.spec.js',
      '/widgets/api_query_widget.spec.js',
      '/widgets/api_request_widget.spec.js',
      '/widgets/api_response_widget.spec.js',
      '/widgets/base_container_view.spec.js',
      '/widgets/base_tree_view.spec.js',
      '/widgets/base_widget.spec.js',

      '/widgets/breadcrumb_widget.spec.js',
      '/widgets/bubble_chart.spec.js',
      '/widgets/citation_graph_facet_widget.spec.js',
      '/widgets/dropdown_widget.spec.js',
      '/widgets/classic_search_widget.spec.js',
      '/widgets/export_widget.spec.js',
      '/widgets/facet_container_view.spec.js',
    //TBD 24/09/14 '/widgets/facet_graph_widget.spec.js',
    //TBD 24/09/14 '/widgets/facet_hier_widget.spec.js',
      '/widgets/facet_widget.spec.js',
      '/widgets/filter_visualizer_widget.spec.js',
    //XXX 24/09/14 '/widgets/facet_zoomable_graph_view.spec.js',
      '/widgets/graphics_widgets.spec.js',
      '/widgets/libraries_all.spec.js',
      '/widgets/library_individual.spec.js',
      '/widgets/library_list_widget.spec.js',
      '/widgets/library_import_widget.spec.js',
      '/widgets/list_of_things_expanding.spec.js',
      '/widgets/list_of_things_widget.spec.js',
      '/widgets/lot_derivates.spec.js',
      '/widgets/metrics_widget.spec.js',
      '/widgets/multi_callback_widget.spec.js',
      '/widgets/navbar_widget.spec.js',
      '/widgets/network_widget.spec.js',
      '/widgets/paper_network_widget.spec.js',
      '/widgets/preferences_widget.spec.js',
      '/widgets/query_info_widget.spec.js',
      '/widgets/reads_graph_facet_widget.spec.js',
      '/widgets/recommender_widget.spec.js',
      '/widgets/resources_widget.spec.js',
      '/widgets/results_render_widget.spec.js',
      '/widgets/search_bar_widget.spec.js',
      '/widgets/sort_widget.spec.js',

    //TBD 24/09/14 '/widgets/similar_widget.spec.js',
      '/widgets/tabs_widget.spec.js',
      '/widgets/user_settings_widget.spec.js',
      '/widgets/wordcloud_widget.spec.js',
      '/widgets/year_graph_facet_widget.spec.js',
      '/widgets/hello_world_widget.spec.js'
  ];
  return tests;
});