/* Generated By:JavaCC: Do not edit this line. InvenioQueryParserConstants.java */
package org.apache.lucene.queryParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InvenioQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _NUM_CHAR = 1;
  /** RegularExpression Id. */
  int _ESCAPED_CHAR = 2;
  /** RegularExpression Id. */
  int _TERM_START_CHAR = 3;
  /** RegularExpression Id. */
  int _TERM_CHAR = 4;
  /** RegularExpression Id. */
  int _WHITESPACE = 5;
  /** RegularExpression Id. */
  int _QUOTED_CHAR = 6;
  /** RegularExpression Id. */
  int _SECOND_OPERATOR = 7;
  /** RegularExpression Id. */
  int _OTHER = 8;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int STAR = 18;
  /** RegularExpression Id. */
  int CARAT = 19;
  /** RegularExpression Id. */
  int QUOTED = 20;
  /** RegularExpression Id. */
  int QUOTED_PARTIAL = 21;
  /** RegularExpression Id. */
  int TERM = 22;
  /** RegularExpression Id. */
  int FUZZY_SLOP = 23;
  /** RegularExpression Id. */
  int PREFIXTERM = 24;
  /** RegularExpression Id. */
  int WILDTERM = 25;
  /** RegularExpression Id. */
  int RANGEIN_START = 26;
  /** RegularExpression Id. */
  int RANGEEX_START = 27;
  /** RegularExpression Id. */
  int REGEX_TERM = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int RANGEIN_TO = 30;
  /** RegularExpression Id. */
  int RANGEIN_END = 31;
  /** RegularExpression Id. */
  int RANGEIN_QUOTED = 32;
  /** RegularExpression Id. */
  int RANGEIN_GOOP = 33;
  /** RegularExpression Id. */
  int RANGEEX_TO = 34;
  /** RegularExpression Id. */
  int RANGEEX_END = 35;
  /** RegularExpression Id. */
  int RANGEEX_QUOTED = 36;
  /** RegularExpression Id. */
  int RANGEEX_GOOP = 37;

  /** Lexical state. */
  int Boost = 0;
  /** Lexical state. */
  int RangeEx = 1;
  /** Lexical state. */
  int RangeIn = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<_NUM_CHAR>",
    "<_ESCAPED_CHAR>",
    "<_TERM_START_CHAR>",
    "<_TERM_CHAR>",
    "<_WHITESPACE>",
    "<_QUOTED_CHAR>",
    "<_SECOND_OPERATOR>",
    "<_OTHER>",
    "<token of kind 9>",
    "<AND>",
    "<OR>",
    "\"!\"",
    "\"+\"",
    "<MINUS>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"*\"",
    "\"^\"",
    "<QUOTED>",
    "<QUOTED_PARTIAL>",
    "<TERM>",
    "<FUZZY_SLOP>",
    "<PREFIXTERM>",
    "<WILDTERM>",
    "\"[\"",
    "\"{\"",
    "<REGEX_TERM>",
    "<NUMBER>",
    "\"TO\"",
    "\"]\"",
    "<RANGEIN_QUOTED>",
    "<RANGEIN_GOOP>",
    "\"TO\"",
    "\"}\"",
    "<RANGEEX_QUOTED>",
    "<RANGEEX_GOOP>",
  };

}
